import Foundation

/// A stable, public identifier for a stored record.
///
/// Native `NodeID` values are assignment order in one file: they
/// differ between two stores built from the same input, and they mean nothing
/// outside the file that issued them. A `RecordID` is generated by this library,
/// stored as an indexed property, and safe to hand to another system, write into
/// a log, or use as a foreign key elsewhere.
public struct RecordID: Hashable, Sendable, Codable, CustomStringConvertible {
  /// The identifier text, of the form `<prefix>_<random>`.
  public let rawValue: String

  /// Wraps an existing identifier, such as one read back from another system.
  public init(_ rawValue: String) {
    self.rawValue = rawValue
  }

  public init(from decoder: any Decoder) throws {
    rawValue = try decoder.singleValueContainer().decode(String.self)
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    try container.encode(rawValue)
  }

  public var description: String { rawValue }

  /// The leading kind marker, or `nil` when the identifier carries none.
  ///
  /// Records read back from the store carry `ev` for evidence and `as` for an
  /// assertion. An identifier supplied by a caller need not follow the
  /// convention, and nothing in this library depends on it.
  public var prefix: String? {
    guard let separator = rawValue.firstIndex(of: "_") else { return nil }
    return String(rawValue[rawValue.startIndex..<separator])
  }

  /// Generates an identifier whose text sorts in creation order.
  ///
  /// The timestamp component makes a listing of raw identifiers readable and
  /// groups records written together, which matters when reading a store with
  /// tools that know nothing about this library.
  static func generate(prefix: String, now: Date = Date()) -> RecordID {
    let milliseconds = UInt64(max(0, (now.timeIntervalSince1970 * 1_000).rounded()))
    let random = UInt64.random(in: 0..<0xFFFF_FFFF)
    return RecordID(
      "\(prefix)_\(String(milliseconds, radix: 36))\(String(random, radix: 36))")
  }
}
